apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "datapusher-plus.fullname" . }}
  labels:
    {{- include "datapusher-plus.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "datapusher-plus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "datapusher-plus.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "datapusher-plus.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          env:
            - name: DATAPUSHER_MAX_CONTENT_LENGTH
              value: {{ index .Values "datapusher-plus" "maxContentLength" | quote }}
            - name: DATAPUSHER_CHUNK_SIZE
              value: {{ index .Values "datapusher-plus" "chunkSize" | quote }}
            - name: DATAPUSHER_CHUNK_INSERT_ROWS
              value: {{ index .Values "datapusher-plus" "insertRows" | quote }}
            - name: DATAPUSHER_DOWNLOAD_TIMEOUT
              value: {{ index .Values "datapusher-plus" "downloadTimeout" | quote }}
            - name: DATAPUSHER_SSL_VERIFY
              value: {{ index .Values "datapusher-plus" "datapusherSslVerify" | quote }}
            - name: DATAPUSHER_REWRITE_RESOURCES
              value: {{ index .Values "datapusher-plus" "datapusherRewriteResources" | quote }}
            - name: DATAPUSHER_REWRITE_URL
              value: {{ index .Values "datapusher-plus" "datapusherRewriteUrl" | quote }}
            - name: DATAPUSHER_DEBUG_MODE
              value: {{ index .Values "datapusher-plus" "debug" | quote }}
            - name: DATAPUSHER_TESTING
              value: {{ index .Values "datapusher-plus" "testing" | quote }}
            - name: DATAPUSHER_WRITE_ENGINE_URL
              value: {{ index .Values "datapusher-plus" "write_engine_url" | quote }}
            - name: DATAPUSHER_PREVIEW_ROWS
              value: {{ index .Values "datapusher-plus" "preview_rows" | quote }}
            - name: DATAPUSHER_DOWNLOAD_PREVIEW_ONLY
              value: {{ index .Values "datapusher-plus" "download_preivew_only" | quote }}
            - name: DATAPUSHER_DEFAULT_EXCEL_SHEET
              value: {{ index .Values "datapusher-plus" "default_excel_sheet" | quote }}
            - name: DATAPUSHER_SORT_AND_DUPE_CHECK
              value: {{ index .Values "datapusher-plus" "sort_and_dupe_check" | quote }}
            - name: DATAPUSHER_DEDUP
              value: {{ index .Values "datapusher-plus" "dedup" | quote }}
            - name: DATAPUSHER_ADD_SUMMARY_STATS_RESOURCE
              value: {{ index .Values "datapusher-plus" "add_summary_stats_resource" | quote }}
            - name: DATAPUSHER_SUMMARY_STATS_WITH_PREVIEW
              value: {{ index .Values "datapusher-plus" "summary_stats_with_preview" | quote }}
            - name: DATAPUSHER_SUMMARY_STATS_OPTIONS
              value: {{ index .Values "datapusher-plus" "summary_stats_options" | quote }}
            - name: DATAPUSHER_AUTO_INDEX_THRESHOLD
              value: {{ index .Values "datapusher-plus" "auto_index_threshold" | quote }}
            - name: DATAPUSHER_AUTO_UNIQUE_INDEX
              value: {{ index .Values "datapusher-plus" "auto_unique_index" | quote }}
            - name: DATAPUSHER_AUTO_INDEX_DATES
              value: {{ index .Values "datapusher-plus" "auto_index_dates" | quote }}
            - name: DATAPUSHER_AUTO_ALIAS
              value: {{ index .Values "datapusher-plus" "auto_alias" | quote }}
            - name: DATAPUSHER_AUTO_ALIAS_UNIQUE
              value: {{ index .Values "datapusher-plus" "auto_alias_unique" | quote }}
            - name: DATAPUSHER_PII_SCREENING
              value: {{ index .Values "datapusher-plus" "pii_screening" | quote }}
            - name: DATAPUSHER_PII_QUICK_SCREEN
              value: {{ index .Values "datapusher-plus" "pii_quick_screen" | quote }}
            - name: DATAPUSHER_PII_FOUND_ABORT
              value: {{ index .Values "datapusher-plus" "pii_found_abort" | quote }}
            - name: DATAPUSHER_PII_SHOW_CANDIDATES
              value: {{ index .Values "datapusher-plus" "pii_show_candidates" | quote }}
            - name: DATAPUSHER_PII_REGEX_RESOURCE_ID_OR_ALIAS
              value: {{ index .Values "datapusher-plus" "pii_regex_resource_id_or_alias" | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
